# Generated by Django 5.0.1 on 2024-01-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('superadmin', '0002_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(related_name='admins', to='organization.organization'),
        ),
    ]
